"""added some columns

Revision ID: 56e9496d2fe1
Revises: 530258e9a11d
Create Date: 2018-04-22 00:13:05.506096

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e9496d2fe1'
down_revision = '530258e9a11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charity', sa.Column('is_form_done', sa.Boolean(), nullable=True))
    op.add_column('donator', sa.Column('current_charity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donator', 'current_charity_id')
    op.drop_column('charity', 'is_form_done')
    # ### end Alembic commands ###
