"""added Charity table

Revision ID: 736215eb55c7
Revises: 05beb7fea3f4
Create Date: 2018-04-21 16:39:05.501393

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736215eb55c7'
down_revision = '05beb7fea3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_name', sa.String(length=64), nullable=True),
    sa.Column('charity_logo', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(length=400), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('connect_public_key', sa.String(length=200), nullable=True),
    sa.Column('connect_access_token', sa.String(length=200), nullable=True),
    sa.Column('connect_user_id', sa.String(length=200), nullable=True),
    sa.Column('connect_refresh_token', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charity_charity_logo'), 'charity', ['charity_logo'], unique=False)
    op.create_index(op.f('ix_charity_charity_name'), 'charity', ['charity_name'], unique=False)
    op.create_index(op.f('ix_charity_connect_access_token'), 'charity', ['connect_access_token'], unique=True)
    op.create_index(op.f('ix_charity_connect_public_key'), 'charity', ['connect_public_key'], unique=False)
    op.create_index(op.f('ix_charity_connect_refresh_token'), 'charity', ['connect_refresh_token'], unique=True)
    op.create_index(op.f('ix_charity_connect_user_id'), 'charity', ['connect_user_id'], unique=True)
    op.create_index(op.f('ix_charity_link'), 'charity', ['link'], unique=False)
    op.add_column('user', sa.Column('is_donator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_donator')
    op.drop_index(op.f('ix_charity_link'), table_name='charity')
    op.drop_index(op.f('ix_charity_connect_user_id'), table_name='charity')
    op.drop_index(op.f('ix_charity_connect_refresh_token'), table_name='charity')
    op.drop_index(op.f('ix_charity_connect_public_key'), table_name='charity')
    op.drop_index(op.f('ix_charity_connect_access_token'), table_name='charity')
    op.drop_index(op.f('ix_charity_charity_name'), table_name='charity')
    op.drop_index(op.f('ix_charity_charity_logo'), table_name='charity')
    op.drop_table('charity')
    # ### end Alembic commands ###
